name: Minecraft Launcher build

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

    workflow_dispatch:
    
jobs:
    linux-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: | 
                sudo apt update
                sudo apt install libcurl4-openssl-dev libx11-6 libx11-dev libwayland-client0 libwayland-server0 libwayland-dev

            - name: compile sdl3
              run: |
                git clone https://github.com/libsdl-org/sdl
                cd sdl
                mkdir build
                cd build
                cmake .. -DSDL_ALSA_SHARED:BOOL="0" -DSDL_DBUS:BOOL="0" -DSDL_DISKAUDIO:BOOL="0" -DSDL_LIBUDEV:BOOL="0" -DSDL_GPU_OPENXR:BOOL="0" -DSDL_FRIBIDI_SHARED:BOOL="0" -DSDL_MMX:BOOL="0" -DSDL_AVX:BOOL="0" -DSDL_POWER:BOOL="0" -DSDL_SSE4_1:BOOL="0" -DSDL_HIDAPI:BOOL="0" -DSDL_DLOPEN_NOTES:BOOL="0" -DSDL_SSE4_2:BOOL="0" -DSDL_DEPS_SHARED:BOOL="0" -DSDL_HIDAPI_LIBUSB_SHARED:BOOL="0" -DSDL_ALSA:BOOL="0" -DSDL_UNINSTALL:BOOL="0" -DSDL_LIBTHAI:BOOL="0" -DSDL_SNDIO_SHARED:BOOL="0" -DSDL_GPU:BOOL="0" -DSDL_PTHREADS:BOOL="1" -DSDL_SYSTEM_ICONV:BOOL="0" -DSDL_SSE3:BOOL="0" -DSDL_SSE2:BOOL="0" -DSDL_HIDAPI_LIBUSB:BOOL="0" -DSDL_KMSDRM:BOOL="0" -DSDL_JACK:BOOL="0" -DSDL_PTHREADS_SEM:BOOL="0" -DSDL_DUMMYVIDEO:BOOL="0" -DSDL_DUMMYAUDIO:BOOL="0" -DSDL_RENDER_VULKAN:BOOL="0" -DSDL_LIBURING:BOOL="0" -DSDL_TRAY:BOOL="0" -DSDL_LIBTHAI_SHARED:BOOL="0" -DSDL_SNDIO:BOOL="0" -DSDL_FRIBIDI:BOOL="0" -DSDL_KMSDRM_SHARED:BOOL="0" -DSDL_TESTS:BOOL="0" -DSDL_AVX512F:BOOL="0" -DSDL_AVX2:BOOL="0" -DSDL_PIPEWIRE_SHARED:BOOL="0" -DSDL_IBUS:BOOL="0" -DSDL_RPATH:BOOL="0" -DSDL_AUDIO:BOOL="0" -DSDL_PIPEWIRE:BOOL="0" -DSDL_SSE:BOOL="0" -DSDL_TEST_LIBRARY:BOOL="0" -DSDL_JOYSTICK:BOOL="0" -DSDL_RELOCATABLE:BOOL="0" -DASOUND_LIB:FILEPATH="/usr/lib/libasound.so" -DSDL_SENSOR:BOOL="0" -DSDL_PULSEAUDIO:BOOL="0" -DSDL_HIDAPI_JOYSTICK:BOOL="0" -DSDL_RENDER_GPU:BOOL="0" -DSDL_HAPTIC:BOOL="0" -DSDL_JACK_SHARED:BOOL="0" -DSDL_GCC_ATOMICS:BOOL="1" -DSDL_PULSEAUDIO_SHARED:BOOL="0" -DSDL_DUMMYCAMERA:BOOL="0" -DSDL_CAMERA:BOOL="0"
                make -j $NPROC

            - name: Build app
              run: |
                mkdir build
                cd build
                cmake ..


