name: Minecraft Launcher build

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

    workflow_dispatch:
    
jobs:
    linux-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: | 
                sudo apt update
                sudo apt install libcurl4-openssl-dev libx11-6 libx11-dev libwayland-client0 libwayland-server0 libwayland-dev

            - name: compile sdl3
              run: |
                git clone https://github.com/libsdl-org/sdl
                cd sdl
                mkdir build
                cd build
                cmake ..
                make -j $NPROC

            - name: Build app
              run: |
                mkdir build
                cd build
                cmake ..


